### ISSUE TITLE
ciel-doctor: Request to add detection for EDITOR environment variable

### ISSUE THREAD

**Issue by CamberLoid** [AOSC-Dev/ciel-rs#11]
When using zsh (shipped by our repository) as shell instead of distro's tarball-shipped `bash` without setting EDITOR environment variable, `ciel` will fail to call `nano` when performing configuration of `source.list`, resulting an unexpected exit. `ciel doctor` should notice the packager about the aforementioned issue. 

---

An example log about this issue (without setting `export EDITOR=nano`)

```
root@Camber-AOSC-TestEnv /buildroot # ciel config -g
✔ Maintainer Information · Camber Huang<camber@aosc.io>
✔ Enable DNSSEC · no
✔ Edit sources.list · yes
error: Could not recognize the configuration.
1 root@Camber-AOSC-TestEnv /buildroot # /
130 root@Camber-AOSC-TestEnv /buildroot # ciel doctor
✓ Systemd D-Bus (systemd 248) seems to be working
✓ Basic I/O operations seem to be working
✓ Required binaries are correctly installed
✓ Filesystem support seems to be sufficient
✓ Environment seems sane (running in kvm)
✓ Disk I/O seems ok
✓ Disk space is sufficient (24.05GiB free of 31.87GiB).
root@Camber-AOSC-TestEnv /buildroot # 
```

**Comment by eatradish** [comment]
Fixed on 7858f54de53162365d6f65cceb3050187963c6e8, closing ...
