### ISSUE TITLE
Feature request: add option to `ciel new` to download arch-specific tarball

### ISSUE THREAD

**Issue by jiegec** [AOSC-Dev/ciel-rs#17]
For example, it can be useful to setup cross architecture ciel workspaces via:

```shell
ciel new --arch riscv64
# download aosc-os_buildkit_xxxxxxxx_riscv64.tar.xz
```

instead of downloading tarball manually.

**Comment by MingcongBai** [comment]
There is actually a `--from-tarball` option, where you can simply specify the URL to the tarball. But this seem like a good idea.

**Comment by Cyanoxygen** [comment]
Just discovered this - there is an ongoing PR which added support for this feature: #18
